# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bq/namek/setup-makefiles.sh

# ADSP
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/bq/namek/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/bq/namek/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so

# Audio
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/bq/namek/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/bq/namek/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/bq/namek/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/bq/namek/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/bq/namek/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/bq/namek/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/bq/namek/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/bq/namek/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/bq/namek/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/bq/namek/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/bq/namek/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/bq/namek/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/bq/namek/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/bq/namek/proprietary/lib/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/bq/namek/proprietary/lib/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so \
    vendor/bq/namek/proprietary/lib/libcam.beautyshot.so:system/lib/libcam.beautyshot.so \
    vendor/bq/namek/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/bq/namek/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/bq/namek/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/bq/namek/proprietary/lib/libmpbase.so:system/lib/libmpbase.so \
    vendor/bq/namek/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122.so:system/vendor/lib/libactuator_lc898122.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122_camcorder.so:system/vendor/lib/libactuator_lc898122_camcorder.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122_camera.so:system/vendor/lib/libactuator_lc898122_camera.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122_F3M2YAP.so:system/vendor/lib/libactuator_lc898122_F3M2YAP.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122_F3M2YAP_camcorder.so:system/vendor/lib/libactuator_lc898122_F3M2YAP_camcorder.so \
    vendor/bq/namek/proprietary/vendor/lib/libactuator_lc898122_F3M2YAP_camera.so:system/vendor/lib/libactuator_lc898122_F3M2YAP_camera.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_common.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_common.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_default_video.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_default_video.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_60fps.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_90fps.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_hfr_120fps.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_preview.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_preview.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_snapshot.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_snapshot.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_s5k3m2_F3M2YAP_snapshot_6fps.so:system/vendor/lib/libchromatix_s5k3m2_F3M2YAP_snapshot_6fps.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_common.so:system/vendor/lib/libchromatix_ov5648_fa_common.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_default_video.so:system/vendor/lib/libchromatix_ov5648_fa_default_video.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_fa_default_video_hd.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_preview.so:system/vendor/lib/libchromatix_ov5648_fa_preview.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_snapshot.so:system/vendor/lib/libchromatix_ov5648_fa_snapshot.so \
    vendor/bq/namek/proprietary/vendor/lib/libchromatix_ov5648_fa_zsl.so:system/vendor/lib/libchromatix_ov5648_fa_zsl.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_ov5648_fa.so:system/vendor/lib/libmmcamera_ov5648_fa.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_qtech_s5k3m2_F3M2YAP_eeprom.so:system/vendor/lib/libmmcamera_qtech_s5k3m2_F3M2YAP_eeprom.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_s5k3m2_F3M2YAP.so:system/vendor/lib/libmmcamera_s5k3m2_F3M2YAP.so \
    vendor/bq/namek/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/bq/namek/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/bq/namek/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/bq/namek/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/bq/namek/proprietary/vendor/lib/libois_lc898122.so:system/vendor/lib/libois_lc898122.so \
    vendor/bq/namek/proprietary/vendor/lib/libois_lc898122_F3M2YAP.so:system/vendor/lib/libois_lc898122_F3M2YAP.so \
    vendor/bq/namek/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/bq/namek/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so \
    vendor/bq/namek/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so

# Camera firmware
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/bq/namek/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/bq/namek/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/bq/namek/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw

# Color convertor
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so

# DRM
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/bq/namek/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/bq/namek/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/bq/namek/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/bq/namek/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/bq/namek/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/bq/namek/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/bq/namek/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/bq/namek/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/bq/namek/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/bq/namek/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/bq/namek/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/bq/namek/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/bq/namek/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/bq/namek/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so

# Graphics
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/bq/namek/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/bq/namek/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/bq/namek/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/bq/namek/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/bq/namek/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/bq/namek/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/bq/namek/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/bq/namek/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/bq/namek/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/bq/namek/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/bq/namek/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/bq/namek/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/bq/namek/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so

# IRQ balance
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance

# Lights
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/lib/hw/lights.msm8916.so:system/lib/hw/lights.msm8916.so

# Media
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/bq/namek/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/bq/namek/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so

# NFC
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so

# Perf
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/bq/namek/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so

# Postprocessing
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/bq/namek/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/bq/namek/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so

# Qualcomm
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/bq/namek/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/bq/namek/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/bq/namek/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/bq/namek/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/bq/namek/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/bq/namek/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/bq/namek/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/bq/namek/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

# Radio
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/bq/namek/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/bq/namek/proprietary/bin/radish:system/bin/radish \
    vendor/bq/namek/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/bq/namek/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/bq/namek/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/bq/namek/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/bq/namek/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/bq/namek/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    vendor/bq/namek/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/bq/namek/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/bq/namek/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/bq/namek/proprietary/vendor/lib/libril-qc-radioconfig.so:system/vendor/lib/libril-qc-radioconfig.so \
    vendor/bq/namek/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/bq/namek/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/bq/namek/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/bq/namek/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so

# Sensors
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/bq/namek/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    vendor/bq/namek/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so

# Thermal
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/bq/namek/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/bq/namek/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

# Time services
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/bq/namek/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/bq/namek/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so

# Touchscreen
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/etc/firmware/A4_07_1.6_AA.fw:system/etc/firmware/A4_07_1.6_AA.fw \
    vendor/bq/namek/proprietary/etc/firmware/A4_07_1.6_AA.raw:system/etc/firmware/A4_07_1.6_AA.raw

# Venus (media) firmware
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/bq/namek/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/bq/namek/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/bq/namek/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/bq/namek/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/bq/namek/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/bq/namek/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Wifi
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/wcnss_service:system/bin/wcnss_service

# Misc
PRODUCT_COPY_FILES += \
    vendor/bq/namek/proprietary/bin/cktnvtool:system/bin/cktnvtool
